### ISSUE TITLE
Do i need to learn native Hibernate or is JPA Hibernate enough?

### ISSUE THREAD

**Issue by mehrdad-maeen** [in28minutes/jpa-with-hibernate#4]
Will employers distinguish between experience working with the native Hibernate API vs. the JPA version of Hibernate when they look at one's resume? I'm going to learn Hibernate soon and I'm thinking I'll just use the JPA interface ... but I don't want to limit myself if its going to make me less marketable.
Thanks for your fantastic courses

**Comment by in28minutes** [comment]
JPA Hibernate covers about 90% of what you want to learn about Hibernate native and it is the standard. Go ahead an learn it. Good Luck.
